### ISSUE TITLE
Add support for additional persisent storage during deployment

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/AWS-Shell#6] opened 2016-04-03 16:21 UTC
EBS & Instance Store
attribute "Storage Type" on the deployment option - persistent (EBS) or non-persistent storage (Instance Store)
if the selection is non-persistent than we use only Instance Store
if the selection is persistent than we'll add an additional EBS volume

**Comment by alonagetzler** [comment] 2016-08-02 12:43
duplicate of #62

**Closed** 2016-08-02 12:44 UTC
Labels: duplicate, F-storage, Version 7.2
