### ISSUE TITLE
when using custome AMI, AWS is not able to get windows credentials as a result our app is not getting win credentials and fail with time out

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#137] opened 2016-07-10 09:13 UTC
STR
Have a reservation with deployed app 
Add undeployed app with costume AMI
Deploy the app

BIR
the deployment is failing with time out but vm is still created in aws

**Comment by alonagetzler** [comment] 2016-07-18 08:28
we shouldn't fail when we can't get credentials

**Comment by alexazarh** [comment] 2016-07-19 10:57
duplicate of #136

**Closed by alexazarh** 2016-07-19 10:57 UTC
Labels: bug, duplicate, P3, Version 7.1
