### ISSUE TITLE
Trying deleting AWS deployed app from RM returns an error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#129] opened 2016-07-06 07:19 UTC
STR
Have an deployed AWS app
Delete the AWS vm from RM

BIR
an error returns

**Comment by alonagetzler** [comment] 2016-07-10 07:42
@tornizanQ  i think that's a bug for Shay's scrum, please make sure there is a bug in the TFS and cancel this one

**Comment by alexazarh** [comment] 2016-07-19 11:06
Duplicate of #136

**Closed by alexazarh** 2016-07-19 11:06 UTC
Labels: bug, duplicate, P2, Version 7.1
