### ISSUE TITLE
Refactor AWS Deploy flow

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/AWS-Shell#47] opened 2016-05-23 11:38 UTC
We should refactor the converters that we use in the deployment driver :
_convert_context_to_deployment_resource_model 
and in the aws_shell.py  :
_convert_to_deployment_resource_model 
convert_to_aws_resource_model

**Comment by alexazarh** [comment] 2016-06-26 15:24
duplicate of #49

**Closed** 2016-06-26 15:24 UTC
Labels: duplicate, F-technical, Version 7.1
