### ISSUE TITLE
Cannot delete AMIs from the RM client if they were not removed from the reservation

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/AWS-Shell#142] opened 2016-07-11 06:54 UTC
1. Have an active AWS reservation.
2. Kill the execution server.
3. End the reservation, causing the teardown to not execute and causing all AWS entities to remain alive. 
4. Terminate the instances via AWS console.
5. Delete the VPC via AWS console.
6. Delete the resources from the RM client.

BIR if you receive the following error:
Could not delete the selected Resource. AttributeError: 'NoneType' object has no attribute 'domain'

**Comment by TaiTheGreat** [comment] 2016-07-11 13:45
This bug also occurs due to the scenario described in Issue #146

**Comment by alonagetzler** [comment] 2016-07-11 14:59
@TaiTheGreat if i understand correctly the flow is event simpler, just have an active AWS reservation with deployed apps and prior to the reservation end try to delete the resources from the RM and it fails. if that is indeed the case than this bug is a bug for Shay's scrum and should be opened in the TFS (and cancelled here).

**Comment by TaiTheGreat** [comment] 2016-07-12 09:13
Ran the scenario, indeed reproduces. 
Adding that the resources can't be deleted from the Inventory either. Same error from both.

**Comment by alexazarh** [comment] 2016-07-19 11:05
Duplicate of #136

**Closed** 2016-07-19 11:05 UTC
Labels: bug, duplicate, New, P2, Version 7.1
