### ISSUE TITLE
Trying to remove AWS deployed app by api commands (DeleteResource, RemoveAppFromReservation) ends with an error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#152] opened 2016-07-13 09:34 UTC
STR
Have a reservation with deployed app in it 
Open api session in python 
Run command DeleteResource or  RemoveAppFromReservation

BIR
The command failed to run and the app is still active

Logs
[TeamServer.Service.txt](https://github.com/QualiSystems/AWS-Shell/files/361150/TeamServer.Service.txt)

**Comment by alexazarh** [comment] 2016-07-19 10:54
duplicate of #145

**Closed** 2016-07-20 16:44 UTC
Labels: bug, duplicate, P2, Version 7.1
