### ISSUE TITLE
Error in case of Refresh after VM termination

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/AWS-Shell#111] opened 2016-06-27 11:40 UTC
In case of Refresh IP Command perior to VM Termination via the AWS  an Error shall be obtained " Out of Sync" by RM. 

Currently there is no error and "Refresh IP Command ended with status completed" message.

**Comment by alonagetzler** [comment] 2016-06-30 07:50
I don't understand this bug
Can you make sure the bug are in the following structure and that the title is detailed enough so you can understand what's the issue from the title.

Steps to reproduce:
1. __
2. __
3. __

Bug is reproduced if ___

Expected behavior:

**Comment by yairbb** [comment] 2016-06-30 09:35
Sure.

STR:
1) Terminate the VM Via the AWS.
2) Trigger "Refresh" Command Via the Portal.
3) An Error shall be obtained.

BIR:

Refresh command was triggered successfully.

**Comment by alexazarh** [comment] 2016-07-21 12:06
@alonagetzler What is the expected behaviour?

**Comment by alonagetzler** [comment] 2016-07-21 12:51
@alexazarh we should throw an error message "The instance doesn't exist."

**Comment by alexazarh** [comment] 2016-07-21 15:03
@alonagetzler 
I think it doesnt makes sense, because as long as the instance is available we should run the command successfully. And when the instance is terminated in aws also the deployed app will be removed. Until the delete command completes the instance is still available.
I think this bug should be canceled.

**Comment by alonagetzler** [comment] 2016-07-24 09:04
@alexazarh this is just for the scenario in which the instance wasn't deleted via CloudShell but via AWS. No throwing any error in this case give the false impression the instance is still available.

**Comment by alexazarh** [comment] 2016-07-24 15:18
@alonagetzler 
If the instance want delete via cloudshell than you will get an error when the instance is not available any more...

**Comment by tornizanQ** [comment] 2016-07-27 12:59
This is the current error

**Comment by alonagetzler** [comment] 2016-07-28 08:41
@tornizanQ that error isn't good enough, still a bug

**Comment by alexazarh** [comment] 2016-08-02 12:19
Lets fix the error message in this command

**Comment by apiddubny** [comment] 2016-09-29 14:39
Fixed in https://github.com/QualiSystems/AWS-Shell/pull/297

**Closed** 2017-02-01 10:18 UTC
Labels: bug, in test, P4, Version 8.0
